#!/usr/bin/env ruby

require 'rubygems'
require 'bundler/setup'
require 'newrelic_plugin'

require 'sidekiq'
require 'sidekiq/api'
require 'redis'

module NewRelic::Sidekiq
  class Agent < NewRelic::Plugin::Agent::Base

    agent_guid 'com.hungerstation.newrelic-sidekiq-agent'
    agent_config_options :name, :uri, :password, :namespace
    agent_version '1.7.1'
    agent_human_labels('Sidekiq') { name }

    attr_reader :sidekiq_stats, :sidekiq_workers

    def initialize(context, options = {})
      raise ArgumentError, "Redis connection URL missing" if options[:uri].nil?
      super
      setup_sidekiq
    end

    def setup_sidekiq
      redis_configuration = { url: uri, id: nil }
      redis_configuration.merge!(password: password) if password
      redis_configuration.merge!(namespace: namespace) if namespace
      Sidekiq.configure_client { |config| config.redis = redis_configuration }
      @sidekiq_stats   = Sidekiq::Stats.new
      @sidekiq_workers = Sidekiq::Workers.new
      @jobs_processed ||= NewRelic::Processor::EpochCounter.new
      @jobs_failed    ||= NewRelic::Processor::EpochCounter.new
    end

    def poll_cycle
      report_metric 'Workers/Working',      'Workers',  sidekiq_workers.size.to_i
      report_metric 'Jobs/Count/Pending',   'Jobs',     sidekiq_stats.queues.values.sum.to_i
      report_metric 'Jobs/Count/Processed', 'Jobs',     sidekiq_stats.processed.to_i
      report_metric 'Jobs/Count/Failed',    'Jobs',     sidekiq_stats.failed.to_i
      report_metric 'Jobs/Count/Scheduled', 'Jobs',     sidekiq_stats.scheduled_size.to_i
      report_metric 'Jobs/Count/Retries',   'Jobs',     sidekiq_stats.retry_size.to_i
      report_metric 'Jobs/Rate/Processed',  'Jobs/sec', @jobs_processed.process(sidekiq_stats.processed.to_i).to_i
      report_metric 'Jobs/Rate/Failed',     'Jobs/sec', @jobs_failed.process(sidekiq_stats.failed.to_i).to_i

      sidekiq_stats.queues.each do |name, enqueued|
        report_metric "Queues/#{name}", 'Enqueued',  enqueued.to_i
        report_metric "Queues/#{name}", 'Latency',   Sidekiq::Queue.new(name).latency.to_f
      end

    rescue Redis::TimeoutError
      raise 'Redis server timeout'
    rescue  Redis::CannotConnectError, Redis::ConnectionError
      raise 'Could not connect to redis'
    rescue Exception => e
      raise "#{e.class}: #{e.message}"
    end

  end

  NewRelic::Plugin::Config.config_file = File.dirname(__FILE__) + '/config/newrelic_plugin.yml'
  NewRelic::Plugin::Setup.install_agent :sidekiq, self

  NewRelic::Plugin::Run.setup_and_run
end
